# Generated by Django 4.2.2 on 2023-06-29 17:55

from django.db import migrations

def add_test_data(apps, schema_editor):
    Product = apps.get_model('suntory', 'Product')
    Product.objects.create(product_name='Product 1', price=10.50, description='Description 1', size=500)
    Product.objects.create(product_name='Product 2', price=25.00, description='Description 2', size=500)
    Product.objects.create(product_name='Product 3', price=37.99, description='Description 3', size=500)
    Product.objects.create(product_name='Product 4', price=150.50, description='Description 4', size=500)
    Product.objects.create(product_name='Product 5', price=205.15, description='Description 5', size=500)
    Product.objects.create(product_name='Product 6', price=145.99, description='Description 6', size=500)
    Product.objects.create(product_name='Product 7', price=98.99, description='Description 7', size=500)
    Product.objects.create(product_name='Product 8', price=225.99, description='Description 8', size=500)
    Product.objects.create(product_name='Product 9', price=500.67, description='Description 9', size=500)
    Product.objects.create(product_name='Product 10', price=1299.25, description='Description 10', size=500)
    Product.objects.create(product_name='Product 11', price=150.99, description='Description 11', size=500)
    Product.objects.create(product_name='Product 12', price=300.99, description='Description 12', size=500)
    Distillery = apps.get_model('suntory', 'Distillery')
    Distillery.objects.create(
        distillery_name='Suntory',
        distillery_country='Japan',
        distillery_description='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent auctor purus massa, ut viverra metus elementum eget. Nam cursus placerat ante, nec ultrices nisl. Sed iaculis eros nibh. Fusce egestas rutrum urna, vitae hendrerit arcu eleifend vestibulum. Donec imperdiet, augue at scelerisque hendrerit, nisl ligula blandit nisi, in feugiat nisl est et orci. Aliquam facilisis ante enim, sed convallis magna bibendum et. Vivamus fermentum elit in ex fermentum, a aliquet ex dictum. Curabitur orci purus, lobortis imperdiet felis sed, finibus sollicitudin lorem. Nullam hendrerit nibh nulla, sit amet dapibus orci scelerisque eu. Vestibulum congue maximus libero quis vestibulum. Ut sed vestibulum libero, et sagittis nisl. Etiam scelerisque semper sapien eget placerat. Pellentesque gravida ipsum ut.'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('suntory', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_test_data),
    ]
