# Generated by Django 4.2.2 on 2023-07-01 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suntory', '0004_distillery_distillery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distillery',
            name='distillery_image',
        ),
        migrations.CreateModel(
            name='DistilleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='distillery_images/default.jpg', upload_to='distillery_images/')),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('distillery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='suntory.distillery')),
            ],
        ),
    ]
