# Generated by Django 4.2.2 on 2023-07-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suntory', '0005_remove_distillery_distillery_image_distilleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillery',
            name='distillery_description',
            field=models.CharField(max_length=2500),
        ),
    ]
